Initial commit of helm-charts for Tuxedo v22
oracle/helm-charts pull request #12
Opened 2022-09-30 21:55 UTC by Diw-dev

Signed-off-by: Diwakar Shetty <diwakar.shetty@oracle.com>

2022-10-04 23:33 UTC, Djelibeybi requested changes
Please remove `helm-chart` from the name of the charts, directories and files. This is the Helm chart repo and these are Helm charts, so that information is redundant.

2022-10-04 23:33 UTC, Djelibeybi commented on tuxedo-loadbal-helm-chart/README.md
> +This is required only if clients have to access the Tuxedo WS (workstation) app over external IP
```suggestion
This service provides client access to the Tuxedo Workstation (WS) service from an external IP address.
```

2022-10-04 23:33 UTC, Djelibeybi commented on tuxedo-loadbal-helm-chart/README.md
> +This helm chart has to be installed before Tuxedo WS (workstation app) tuxedows-helm-chart helm chart.
```suggestion
The `LoadBalancer` service must be running before deploying Tuxedo Workstation (WS) using the `tuxedows` Helm chart.
```

2022-10-04 23:33 UTC, Djelibeybi commented on tuxedo-loadbal-helm-chart/README.md
> +To install this helm-chart, run the below command:
```suggestion
To create a `LoadBalancer` using this Helm chart, run:
```

2022-10-04 23:33 UTC, Djelibeybi commented on tuxedo-loadbal-helm-chart/README.md
> +```
````suggestion
```shell
helm install tuxedo-loadbal-install tuxedo-loadbal
```
````

2022-10-04 23:33 UTC, Djelibeybi commented on tuxedo-loadbal-helm-chart/Chart.yaml
> +name: tuxedo-loadbal-helm-chart
```suggestion
name: tuxedo-loadbal
```

2022-10-05 23:44 UTC, streamnsight commented
@Diw-dev 
Just a comment/question here as I stumble upon this PR: 
Why 2 charts? Why not have the load balancer as an option for a single chart?

2022-10-06 21:15 UTC, Diw-dev commented
Incorporated the review comments by the Tuxedo documentation team for the Tuxedo WS server README.md as well as the Load Balancer README.md.

2022-10-06 21:16 UTC, Diw-dev commented
> @Diw-dev Just a comment/question here as I stumble upon this PR: Why 2 charts? Why not have the load balancer as an option for a single chart?

I have combined the two charts (as subcharts) under one common directory "tuxedo" now. This will make the layout neater.

2022-10-06 21:40 UTC, Djelibeybi requested changes

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/README.md
> +* [Tuxedo WS server](./charts/tuxedo-ws) : Sample Tuxedo WS (workstation) SSL server.
```suggestion
* [Tuxedo Workstation SSL server](./charts/tuxedo-ws): Sample Tuxedo Workstation (WS) SSL server.
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/README.md
> +* [Load Balancer service](./charts/loadbal) : Service to provide an external IP for Tuxedo WS server, if required.
```suggestion
* [Load Balancer service](./charts/loadbal): Service to provide an external IP for a Tuxedo WS server, if required.
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/charts/loadbal/README.md
> +The `LoadBalancer` service must be running before deploying Tuxedo Workstation (WS) using the `tuxedo-ws` Helm chart.
```suggestion
The `LoadBalancer` service must be running before deploying Tuxedo WS using the `tuxedo-ws` Helm chart.
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-ws/README.md
> +# Oracle Tuxedo WS (workstation) SSL server
```suggestion
# Oracle Tuxedo Workstation SSL server
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-ws/README.md
> +This helm chart creates the Tuxedo WS (workstation) SSL server with two services: `BASICWS` and `TOUPPER`
```suggestion
This Helm chart creates an Oracle Tuxedo Workstation (WS) SSL server with two services: `BASICWS` and `TOUPPER`
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-ws/README.md
> +  1. Build the `tuxedows_svr` container image using the [Oracle Tuxedo WS App](https://github.com/oracle/docker-images/OracleTuxedo/core/samples/ws_ssl_svr/).
```suggestion
  1. Build a `tuxedows_svr` container image using the [sample Oracle Tuxedo WS App](https://github.com/oracle/docker-images/OracleTuxedo/core/samples/ws_ssl_svr/).
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-ws/README.md
> +  2. Upload the container image to a private container registry. This location will be used in the `helm install` step later in this procedure.
```suggestion
  2. Upload the `tuxedows_svr` image you built in step 1 to a private container registry and take a note of its location. This location will be used in the `helm install` step later in this procedure.
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-ws/README.md
> +     This IP will be used to access the tuxedo services on port 9055, 9060 and 2071 to 2075 from outside the kubernetes cluster.
```suggestion
  3. If you want to be able to connect to the Tuxedo WS server from an external source, use the `loadbal` helm chart to obtain an external IP address:
  
     ```shell
     EXT_IP=$(kubectl get service --namespace default tuxedo-loadbal-svc --output jsonpath='{.status.loadBalancer.ingress[0].ip}')
     ```

     This IP address will provide external access to the Tuxedo services running on your Kubernetes cluster on ports 9055, 9060 and 2071 to 2075.
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-ws/README.md
> +To create the `Tuxedo WS SSL server` using this Helm chart, run the following command:
```suggestion
To create a Tuxedo WS SSL server using this Helm chart, run:
```

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-ws/values.yaml
> +  repository: iad.ocir.io/paasdevblockchain/oracle/tuxedows_svr
```suggestion
  repository: 
```

Thankfully, this URL doesn't actually work because that would have been a much bigger issue.

2022-10-06 21:40 UTC, Djelibeybi commented on tuxedo/values.yaml
> +  repository: iad.ocir.io/paasdevblockchain/oracle/tuxedows_svr
```suggestion
  repository: 
```

2022-10-06 23:28 UTC, streamnsight commented
> 

I meant, I think it should be a single chart, with a flag like `deployLoadBalancer` in the `values.yaml` that the user can choose to set to `true` or `false` (with a default to `false` if that is a sensible default) and then in the template, render the LoadBalancer yaml when the flag is true. 
I assume that the LoadBalancer itself is useless without the server deployment, and it is either you deploy the server with or without the LB.

You can do this by using the following syntax:

```yaml
{{- if .Values.deployLoadBalancer }}
-----
your template yaml
{{- end }}
```

2022-10-07 00:18 UTC, Diw-dev commented
> > 
> 
> I meant, I think it should be a single chart, with a flag like `deployLoadBalancer` in the `values.yaml` 
> 
> ```yaml
> {{- if .Values.deployLoadBalancer }}
> -----
> your template yaml
> {{- end }}
> ```

Yes, I saw this approach in some other helm charts. However, the thing is, the helm-install for tuxedows deployment needs the external IP generated by the load balancer deployment. Hence they are kind of independent installs. 

Also, once the LB is installed, it won't needed to be upgraded anytime soon since the external IP changes every time the helm install for LB is done and that is not desired. While the helm install for tuxedows can be installed/upgraded as many times as required without any such concerns.

2022-10-07 01:28 UTC, streamnsight commented
> 

I see your point.
It's still possible to do it in one chart and automate LB external IP discovery. The LB would not be affected by updates if the LB part of the chart doesn't change. What you'd need then is an init container that waits for the LB to be ready and have its External IP published, and then looking the IP up in the init script on the Tuxedo startup.
Now, that means an init container that calls the kubernetes API to lookup the external IP of the service, which means setting up a ClusterRole, ClusterRoleBinding for the service account to authorize this in the cluster. Admittedly, it is more complex, but would automate the process.
Now if the IP is needed by Tuxedo because it does its SSL cert delivery and termination, you might want to consider relegating this to whatever service mesh the end-user will use. I'd assume most production deployments would be part of a mesh that can handle TLS between the gateway and the server and manage cert delivery etc...

2022-10-10 14:32 UTC, Diw-dev commented
> I see your point. It's still possible to do it in one chart and automate LB external IP discovery. 

This is a good option and thanks for the detailed explanation. However, at this point, LB is just one of the alternatives to expose an external IP. We are also looking into other popular options too and hence would like to keep the sample app independent of the mechanism of generation of external IP, at least for now.

2022-10-10 18:25 UTC, Djelibeybi approved these changes

2022-10-10 18:25 UTC, merged