Tuxedo v22.1.0.0.0 - Added SALT bankapp sample application helm charts
oracle/helm-charts pull request #15
Opened 2022-11-24 00:38 UTC by Diw-dev

Signed-off-by: Diwakar Shetty <diwakar.shetty@oracle.com>

2022-11-28 21:39 UTC, Diw-dev commented
@Djelibeybi 
Hello Avi, could not figure out how to add you as a reviewer through the Github menu. Hence this message to please help me with reviewing this helm chart PR ?

2022-11-28 22:15 UTC, Djelibeybi requested changes

2022-11-28 22:15 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +BANKAPP_SITE="bankapp.oracle.com"     # can be any website name (but not IP address) of your choice
Never use `oracle.com` in any examples. Always use `example.com`.

2022-11-28 22:15 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +openssl req -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -subj '/O=Oracle Inc/CN=does-not-matter' -keyout root-ca.private.key -out root-ca.crt
Remove `Oracle Inc` and replace with `Example Company`

2022-11-28 22:15 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +  --set IngressTLSHosts=`<$BANKAPP_SITE used earlier, e.g. bankapp.oracle.com>`  \
Replace `oracle.com` with `example.com`

2022-11-28 22:15 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/templates/NOTES.txt
> +  export BANKAPP_SITE=<same value as what was used in one of the earlier steps. e.g. bankapp.oracle.com.>
Replace `oracle.com` with `example.com`

2022-11-28 22:15 UTC, Djelibeybi commented on tuxedo/README.md
> +* [Tuxedo SALT bankapp sample](./charts/tuxedo-bankapp): Sample Tuxedo SALT bankapp sample application.
Please use the correct product name as is used in the `docker-images` repo.

2022-11-28 22:15 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +# Oracle Tuxedo `bankapp` Sample Application
Please use the same product name as the container image

2022-11-30 21:13 UTC, Djelibeybi requested changes
Could you please also add a disclaimer in the `README.md` that this Helm chart should only be deployed internally and used for learning and development purposes and should not be deployed to any production or externally accessible environments?

2022-11-30 21:13 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
>  This Helm chart creates an Oracle Tuxedo  sample `bankapp` application with services sch as `INQUIRY`, `TRANSFER`, `DEPOSIT`, `WITHDRAWAL` and other similar services.
```suggestion
This Helm chart creates a sample Oracle Tuxedo `bankapp` application with multiple services including `INQUIRY`, `TRANSFER`, `DEPOSIT` and `WITHDRAWAL`.
```

2022-12-01 00:51 UTC, Djelibeybi requested changes

2022-12-01 00:51 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +* To run the `Tuxedo bankapp sample application`, install this helm chart by running the following command:
```suggestion
* To run the Tuxedo `bankapp` sample application, install this Helm chart by running the following command:
```

2022-12-01 00:51 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +```
Please paste the full JSON output so that it's still valid JSON.

2022-12-01 00:51 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +If clients external to the Kubernetes cluster should be able to access the bankapp, then you can install Istio Ingress to obtain an external IP along with SSL support.
```suggestion
Istio Ingress can be installed to provide an external IP and SSL support which will allow you to connect to the `bankapp` application from clients external to the Kubernetes cluster.
```

2022-12-01 00:51 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +* Install Istio `demo` profile using the [Istio Installation Guides](https://istio.io/latest/docs/setup/install/). This should result in the istio-ingressgateway service being installed, along with a
```suggestion
* Install Istio `demo` profile using the [Istio installation guide](https://istio.io/latest/docs/setup/install/). The `demo` profile will install an `istio-ingressgateway` service and output an `EXTERNAL-IP` value, as shown in the following sample listing:
```

2022-12-01 00:51 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +* To run the `Tuxedo bankapp sample application`, install this helm chart by running the following command:
```suggestion
* To run the Tuxedo `bankapp` sample application, install this Helm chart by running the following command:
```

2022-12-01 00:51 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/templates/NOTES.txt
> +  export BANKAPP_SITE=<same value as what was used in one of the earlier steps. e.g. bankapp.oracle.com.>
This still needs to be changed.

2022-12-01 20:13 UTC, Djelibeybi requested changes
Remember you also need to run `package_chart.sh` to create the tarball, update the chart repo metadata and commit the tarball and updated `index.yaml` so that `oracle/tuxedo-bankapp` works correctly.

2022-12-01 20:13 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +* Build a `tuxedo-bankapp` container image using the [Oracle Tuxedo bankapp image](https://github.com/oracle/docker-images/tree/main/OracleTuxedo/salt/samples/bankapp)
```suggestion
* Build a Tuxedo `bankapp` container image using the [Oracle Tuxedo `bankapp` image](https://github.com/oracle/docker-images/tree/main/OracleTuxedo/salt/samples/bankapp)
```

2022-12-01 20:13 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +* Push the `tuxedo-bankapp` image that you built in the preceding step to a private container registry and note down its location. This location will be used in the `helm install` step later in this
```suggestion
* Push the Tuxedo `bankapp` image that you built in the preceding step to a private container registry and note down its location. This location will be used in the `helm install` step later in this procedure.
```

2022-12-01 20:13 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +  tuxedo-bankapp-install tuxedo/charts/tuxedo-bankapp
```suggestion
  tuxedo-bankapp-install oracle/tuxedo-bankapp
```

2022-12-01 20:13 UTC, Djelibeybi commented on tuxedo/charts/tuxedo-bankapp/README.md
> +  tuxedo-bankapp-install tuxedo/charts/tuxedo-bankapp
```suggestion
  tuxedo-bankapp-install oracle/tuxedo-bankapp
```

2022-12-01 22:52 UTC, Diw-dev commented
> Remember you also need to run `package_chart.sh` to create the tarball, update the chart repo metadata and commit the tarball and updated `index.yaml` so that `oracle/tuxedo-bankapp` works correctly.

Added the `tuxedo-bankapp-0.1.0.tgz` and updated the `index.yaml` now. Thanks.

2022-12-04 18:31 UTC, Djelibeybi approved these changes

2022-12-04 18:33 UTC, Djelibeybi approved these changes

2022-12-04 18:33 UTC, merged